# Generated by Django 4.1.5 on 2023-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0004_alter_users_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='propic',
            field=models.ImageField(default=None, upload_to='propic'),
        ),
    ]
